import React from 'react';
import { glyphs, brandGlyphs, ICON_VIEWBOX, BRAND_VIEWBOX } from './glyphs.js';

/* Material Symbols Outlined (weight 400) as real SVG vectors inheriting
   currentColor. Never font ligatures, never a glyph name rendered as text.

   Icons render SYNCHRONOUSLY from inlined path data (components/core/glyphs.js,
   generated by `npm run assets`). That matters for three reasons:

   - There is no asset base URL to configure. The old implementation derived one
     from the design-system bundle's own <script src>, which works in a card and
     does not exist at all in a bundled React app.
   - There is no request, so no placeholder frame, no CDN dependency, and no
     toolbar that empties when a network is restricted.
   - It is correct in SSR. An icon that arrives in an effect renders nothing on
     the server and causes a hydration flash on the client.

   A name that is not in the inlined set still falls back to fetching, so a
   consumer can use any Material Symbol without regenerating the set — it just
   pays a request for it. For a permanent addition, call `registerGlyphs` from
   ./glyphs.js, or re-run `npm run assets` once the name is used in source. */

/* Fetch bases, used only for names outside the inlined set. */
export const MATERIAL_SYMBOLS_BASE = 'https://cdn.jsdelivr.net/npm/@material-symbols/svg-400/outlined/';
export const BRAND_ICON_BASE = 'https://cdn.jsdelivr.net/npm/simple-icons@13/icons/';

const cache = new Map();

function fetchPath(url) {
  if (!cache.has(url)) {
    const pending = typeof fetch === 'function'
      ? fetch(url)
        .then((r) => (r.ok ? r.text() : null))
        .catch(() => null)
        .then((text) => {
          const m = text && text.match(/<path[^>]*\sd="([^"]+)"/);
          if (!m) console.warn('[LAMP] icon not found: ' + url);
          return m ? m[1] : null;
        })
      : Promise.resolve(null);
    cache.set(url, pending);
  }
  return cache.get(url);
}

/**
 * Resolves a glyph to its path data. Inlined glyphs return on the first render;
 * anything else resolves after a fetch and re-renders once.
 */
function usePath(name, table, base) {
  const inlined = table[name];
  const [fetched, setFetched] = React.useState(() => (inlined ? null : cache.get(base + name) || null));

  React.useEffect(() => {
    if (inlined || !name) return undefined;
    let alive = true;
    fetchPath(base + name + '.svg').then((d) => { if (alive && d) setFetched(d); });
    return () => { alive = false; };
  }, [name, inlined, base]);

  return inlined || (typeof fetched === 'string' ? fetched : null);
}

/* A glyph that cannot be resolved renders a visible placeholder rather than an
   invisible gap, so a bad name is caught in review instead of shipping as a
   control with no meaning. */
function Placeholder({ size }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true" style={{ display: 'block' }}>
      <rect x="4.5" y="4.5" width="15" height="15" rx="2" fill="none" stroke="currentColor" strokeWidth="1.5" opacity="0.45" />
    </svg>
  );
}

export function Icon({ name, size = 16, className = '', style, label, ...rest }) {
  const key = String(name).replace(/-/g, '_');
  const d = usePath(key, glyphs, MATERIAL_SYMBOLS_BASE);
  return (
    <span
      className={className}
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : 'true'}
      style={{ display: 'inline-flex', flex: 'none', width: size, height: size, color: 'currentColor', ...style }}
      {...rest}
    >
      {d ? (
        <svg width={size} height={size} viewBox={ICON_VIEWBOX} fill="currentColor" aria-hidden="true" style={{ display: 'block' }}>
          <path d={d} />
        </svg>
      ) : (
        <Placeholder size={size} />
      )}
    </span>
  );
}

export function BrandIcon({ slug, size = 16, color, className = '', style, label, ...rest }) {
  const key = String(slug).toLowerCase();
  const d = usePath(key, brandGlyphs, BRAND_ICON_BASE);
  return (
    <span
      className={className}
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : 'true'}
      style={{ display: 'inline-flex', flex: 'none', width: size, height: size, color: color || 'var(--text-secondary)', ...style }}
      {...rest}
    >
      {d ? (
        <svg width={size} height={size} viewBox={BRAND_VIEWBOX} fill="currentColor" aria-hidden="true" style={{ display: 'block' }}>
          <path d={d} />
        </svg>
      ) : (
        <Placeholder size={size} />
      )}
    </span>
  );
}
