/* GENERATED by tools/build-package.mjs — do not edit.
 *
 * The public surface of @lamp/design-system. Every export re-exports from
 * project/components, which is the single source of truth shared with the
 * design-system bundle. */

/* canvas */
export { CanvasContextMenu } from '../../../project/components/canvas/CanvasContextMenu.jsx';
export { GSAP_CDN, GSAP_EASE, GSAP_DURATION, setGsap, loadGsap, useGsap, prefersReducedMotion } from '../../../project/components/canvas/CanvasMotion.jsx';
export { CanvasSurface, SnapGuide } from '../../../project/components/canvas/CanvasSurface.jsx';
export { CanvasToolbar, CanvasZoomControls, CanvasObjectToolbar, CanvasMinimap } from '../../../project/components/canvas/CanvasToolbar.jsx';
export { SnapField } from '../../../project/components/canvas/SnapField.jsx';

/* chat */
export { ChatStatus, AgentChat } from '../../../project/components/chat/AgentChat.jsx';
export { ChatQuickReplies, ChatComposer } from '../../../project/components/chat/ChatComposer.jsx';
export { ChatAvatar, ChatActivity, ChatCitation, ChatDayDivider, ChatMessage } from '../../../project/components/chat/ChatMessage.jsx';

/* core */
export { Badge } from '../../../project/components/core/Badge.jsx';
export { Button, SplitButton } from '../../../project/components/core/Button.jsx';
export { Card } from '../../../project/components/core/Card.jsx';
export { Divider } from '../../../project/components/core/Divider.jsx';
export { EnvironmentPill } from '../../../project/components/core/EnvironmentPill.jsx';
export { MATERIAL_SYMBOLS_BASE, BRAND_ICON_BASE, Icon, BrandIcon } from '../../../project/components/core/Icon.jsx';
export { IconButton } from '../../../project/components/core/IconButton.jsx';
export { Kbd } from '../../../project/components/core/Kbd.jsx';
export { Panel } from '../../../project/components/core/Panel.jsx';
export { STATUS, StatusDot, StatusBadge } from '../../../project/components/core/StatusBadge.jsx';
export { Tag } from '../../../project/components/core/Tag.jsx';
export { Tooltip } from '../../../project/components/core/Tooltip.jsx';
export { ICON_VIEWBOX, BRAND_VIEWBOX, glyphs, brandGlyphs, registerGlyphs } from '../../../project/components/core/glyphs.js';
export { useMergedRefs } from '../../../project/components/core/refs.js';

/* dashboard */
export { DashboardCard, DashboardGrid, StatGrid } from '../../../project/components/dashboard/DashboardCard.jsx';
export { PageHeader, DashboardPage, SectionHeader } from '../../../project/components/dashboard/PageHeader.jsx';

/* data */
export { BarChart } from '../../../project/components/data/BarChart.jsx';
export { DATAVIZ, ChartLegend, ChartFrame, ChartTooltip, seriesColor } from '../../../project/components/data/ChartFrame.jsx';
export { ContextBreakdown } from '../../../project/components/data/ContextBreakdown.jsx';
export { DataTable } from '../../../project/components/data/DataTable.jsx';
export { DonutChart } from '../../../project/components/data/DonutChart.jsx';
export { Heatmap, heatColor } from '../../../project/components/data/Heatmap.jsx';
export { HexHeatmap } from '../../../project/components/data/HexHeatmap.jsx';
export { LineChart } from '../../../project/components/data/LineChart.jsx';
export { MetricCard } from '../../../project/components/data/MetricCard.jsx';
export { ProgressBar, UsageMeter } from '../../../project/components/data/ProgressBar.jsx';
export { ScatterPlot } from '../../../project/components/data/ScatterPlot.jsx';
export { Sparkline } from '../../../project/components/data/Sparkline.jsx';
export { StackedBar } from '../../../project/components/data/StackedBar.jsx';
export { VIZ_TIERS, Viz } from '../../../project/components/data/Viz.jsx';

/* feedback */
export { EmptyState } from '../../../project/components/feedback/EmptyState.jsx';
export { ErrorState } from '../../../project/components/feedback/ErrorState.jsx';
export { InlineNotification, Toast, ToastStack } from '../../../project/components/feedback/InlineNotification.jsx';
export { Modal, CriticalConfirmation, Drawer, Popover } from '../../../project/components/feedback/Modal.jsx';
export { Skeleton, Spinner } from '../../../project/components/feedback/Skeleton.jsx';

/* forms */
export { Checkbox } from '../../../project/components/forms/Checkbox.jsx';
export { CodeFrame } from '../../../project/components/forms/CodeFrame.jsx';
export { Field } from '../../../project/components/forms/Field.jsx';
export { KeyValueInput } from '../../../project/components/forms/KeyValueInput.jsx';
export { VariableToken, PromptEditor } from '../../../project/components/forms/PromptEditor.jsx';
export { Radio, RadioGroup } from '../../../project/components/forms/Radio.jsx';
export { Select } from '../../../project/components/forms/Select.jsx';
export { Slider } from '../../../project/components/forms/Slider.jsx';
export { Switch } from '../../../project/components/forms/Switch.jsx';
export { TagInput } from '../../../project/components/forms/TagInput.jsx';
export { TextInput, SearchInput, NumberInput, SecretField } from '../../../project/components/forms/TextInput.jsx';
export { Textarea } from '../../../project/components/forms/Textarea.jsx';

/* inspector */
export { InspectorField } from '../../../project/components/inspector/InspectorField.jsx';
export { InspectorHeader, InspectorTabs, InspectorFooter, InspectorPanel } from '../../../project/components/inspector/InspectorPanel.jsx';
export { InspectorSection, PropertyRow } from '../../../project/components/inspector/InspectorSection.jsx';

/* memory */
export { FACT_TYPES, MEMORY_SCOPES, MemoryBadge, MemoryScope, MemoryConfidence } from '../../../project/components/memory/MemoryBadge.jsx';
export { MemoryConflict } from '../../../project/components/memory/MemoryConflict.jsx';
export { MemoryFact } from '../../../project/components/memory/MemoryFact.jsx';
export { MemoryGraph } from '../../../project/components/memory/MemoryGraph.jsx';
export { MemoryScopeBar } from '../../../project/components/memory/MemoryScopeBar.jsx';
export { MemoryTimeline } from '../../../project/components/memory/MemoryTimeline.jsx';
export { MemoryUsageBar } from '../../../project/components/memory/MemoryUsageBar.jsx';

/* navigation */
export { AppShell } from '../../../project/components/navigation/AppShell.jsx';
export { Breadcrumb } from '../../../project/components/navigation/Breadcrumb.jsx';
export { CommandPalette } from '../../../project/components/navigation/CommandPalette.jsx';
export { FilterBar, Pagination } from '../../../project/components/navigation/FilterBar.jsx';
export { GlobalHeader } from '../../../project/components/navigation/GlobalHeader.jsx';
export { ObjectTree } from '../../../project/components/navigation/ObjectTree.jsx';
export { SegmentedControl } from '../../../project/components/navigation/SegmentedControl.jsx';
export { SideNav, NavSection, NavItem } from '../../../project/components/navigation/SideNav.jsx';
export { StatusBar } from '../../../project/components/navigation/StatusBar.jsx';
export { Tabs } from '../../../project/components/navigation/Tabs.jsx';
export { WorkspaceSwitcher } from '../../../project/components/navigation/WorkspaceSwitcher.jsx';

/* objects */
export { AGENT_SIZES, AgentHex } from '../../../project/components/objects/AgentHex.jsx';
export { AgentIsland } from '../../../project/components/objects/AgentIsland.jsx';
export { BondEdge, BondLayer } from '../../../project/components/objects/BondEdge.jsx';
export { EntityChip } from '../../../project/components/objects/EntityChip.jsx';
export { GenieCard } from '../../../project/components/objects/GenieCard.jsx';
export { HexLattice, HexCenter, hexCenter } from '../../../project/components/objects/HexLattice.jsx';
export { ObjectRow, ObjectList } from '../../../project/components/objects/ObjectRow.jsx';
export { PlaybookCluster } from '../../../project/components/objects/PlaybookCluster.jsx';
export { SKILL_SIZES, SkillOrb } from '../../../project/components/objects/SkillOrb.jsx';
export { TOOL_SIZES, ToolTile, ToolRow } from '../../../project/components/objects/ToolTile.jsx';

/* patterns */
export { BUSINESS_PROCESSES, BLANK_PROCESS, MatchProcess, ProcessProposal, matchProcess } from '../../../project/components/patterns/BusinessProcess.jsx';
export { Message, MessageList, Composer, Conversation } from '../../../project/components/patterns/Conversation.jsx';
export { BuildGenie, GenieBlueprint, buildGenie } from '../../../project/components/patterns/GenieBlueprint.jsx';
export { IntegrationCard } from '../../../project/components/patterns/IntegrationCard.jsx';
export { LearnedPattern } from '../../../project/components/patterns/LearnedPattern.jsx';
export { MobileShell } from '../../../project/components/patterns/MobileShell.jsx';
export { ObservedProcess } from '../../../project/components/patterns/ObservedProcess.jsx';
export { PermissionCell, PermissionMatrix, RoleBadge } from '../../../project/components/patterns/PermissionMatrix.jsx';
export { PlaybookComposer } from '../../../project/components/patterns/PlaybookComposer.jsx';
export { VoiceWaveform, VoiceButton } from '../../../project/components/patterns/VoiceButton.jsx';

/* runtime */
export { ApprovalCard, HumanCheckpoint } from '../../../project/components/runtime/ApprovalCard.jsx';
export { EnvironmentBanner } from '../../../project/components/runtime/EnvironmentBanner.jsx';
export { KillSwitch, SafetyControls } from '../../../project/components/runtime/KillSwitch.jsx';
export { LiveActivityIndicator } from '../../../project/components/runtime/LiveActivityIndicator.jsx';
export { ReadinessCheck } from '../../../project/components/runtime/ReadinessCheck.jsx';
export { RunSummary } from '../../../project/components/runtime/RunSummary.jsx';
export { RunStep, RunTimeline } from '../../../project/components/runtime/RunTimeline.jsx';
export { SimulationBar } from '../../../project/components/runtime/SimulationBar.jsx';
export { SimulationStep } from '../../../project/components/runtime/SimulationStep.jsx';
