/**
 * Builds packages/react — the npm package a React app installs.
 *
 * The design-system sources in project/components are already real ES modules
 * with real imports, so this is a packaging step rather than a rewrite: it
 * generates the barrel, bundles ESM and CJS, flattens the per-component .d.ts
 * files into one declaration file, and inlines the CSS import graph into a
 * single stylesheet with its font URLs rewritten.
 *
 * What this does NOT do is fork the components. project/components stays the
 * single source of truth — the design-system bundle and the npm package are two
 * outputs of it, so a fix lands in both.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, statSync, copyFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PROJECT = join(ROOT, 'project');
const PKG = join(ROOT, 'packages/react');
const SRC = join(PKG, 'src');
const DIST = join(PKG, 'dist');

const manifest = JSON.parse(readFileSync(join(PROJECT, '_ds_manifest.json'), 'utf8'));

/* ------------------------------------------------------------------ barrel */

/**
 * Helpers the design-system namespace deliberately hides.
 *
 * The bundle only publishes capitalized exports, which is right for a global
 * namespace and wrong for a module: `setGsap` and `registerGlyphs` are exactly
 * the entry points a React consumer needs, and hiding them because of a naming
 * convention would be a packaging artifact leaking into the API.
 */
const EXTRA_EXPORTS = [
  ['components/canvas/CanvasMotion.jsx', ['setGsap', 'loadGsap', 'useGsap', 'prefersReducedMotion']],
  ['components/core/glyphs.js', ['glyphs', 'brandGlyphs', 'registerGlyphs']],
  ['components/core/refs.js', ['useMergedRefs']],
  ['components/objects/HexLattice.jsx', ['hexCenter']],
  ['components/canvas/SnapField.jsx', ['freeCells', 'freeCellAt']],
  ['components/data/ChartFrame.jsx', ['seriesColor']],
  ['components/data/Heatmap.jsx', ['heatColor']],
  ['components/patterns/BusinessProcess.jsx', ['matchProcess']],
  ['components/patterns/GenieBlueprint.jsx', ['buildGenie']],
];

/* name -> source file, grouped so the barrel reads like the system's own map */
const bySource = new Map();
for (const { name, sourcePath } of manifest.components) {
  if (!bySource.has(sourcePath)) bySource.set(sourcePath, []);
  bySource.get(sourcePath).push(name);
}
for (const [sourcePath, names] of EXTRA_EXPORTS) {
  if (!bySource.has(sourcePath)) bySource.set(sourcePath, []);
  for (const n of names) if (!bySource.get(sourcePath).includes(n)) bySource.get(sourcePath).push(n);
}

const groupOf = (p) => p.split('/')[1];
const groups = {};
for (const sourcePath of [...bySource.keys()].sort()) {
  const g = groupOf(sourcePath);
  (groups[g] = groups[g] || []).push(sourcePath);
}

const barrel = [
  '/* GENERATED by tools/build-package.mjs — do not edit.',
  ' *',
  ' * The public surface of @lamp/design-system. Every export re-exports from',
  ' * project/components, which is the single source of truth shared with the',
  ' * design-system bundle. */',
  '',
];
for (const g of Object.keys(groups).sort()) {
  barrel.push('/* ' + g + ' */');
  for (const sourcePath of groups[g]) {
    const names = bySource.get(sourcePath);
    const from = relative(SRC, join(PROJECT, sourcePath)).split('\\').join('/');
    barrel.push(`export { ${names.join(', ')} } from '${from}';`);
  }
  barrel.push('');
}

mkdirSync(SRC, { recursive: true });
writeFileSync(join(SRC, 'index.js'), barrel.join('\n'));

/* ------------------------------------------------------------------ bundle */

if (existsSync(DIST)) rmSync(DIST, { recursive: true });
mkdirSync(DIST, { recursive: true });

const shared = {
  entryPoints: [join(SRC, 'index.js')],
  bundle: true,
  /* react/react-dom stay external so the consumer's copy is the only one. gsap
     is never imported — it is injected through setGsap — so it needs no entry
     here at all, which is the point of that design. */
  external: ['react', 'react-dom', 'react/jsx-runtime'],
  jsx: 'transform',
  loader: { '.jsx': 'jsx', '.js': 'jsx' },
  target: ['es2019', 'chrome90', 'firefox90', 'safari14'],
  /* No keepNames. React reads a forwardRef component's devtools name off its
     inner function, and esbuild leaves those names alone in this unminified
     build — so devtools reads correctly in development, which is when anyone
     looks. keepNames would bake a __name() call next to every component to
     survive the CONSUMER's minifier too, at ~40kB, and a production build is
     not where you read component names. The other option, a displayName
     statement per component, is a top-level side effect on an exported binding
     and stops the package tree-shaking altogether. */
  logLevel: 'warning',
};

await esbuild.build({ ...shared, format: 'esm', outfile: join(DIST, 'index.mjs') });
await esbuild.build({ ...shared, format: 'cjs', outfile: join(DIST, 'index.cjs') });

/* ------------------------------------------------------------------- types */

const walk = (dir, out = []) => {
  for (const e of readdirSync(dir)) {
    const f = join(dir, e);
    if (statSync(f).isDirectory()) walk(f, out);
    else out.push(f);
  }
  return out;
};

const declFiles = walk(join(PROJECT, 'components')).filter((f) => f.endsWith('.d.ts')).sort();

const types = [
  '/* GENERATED by tools/build-package.mjs — do not edit.',
  ' *',
  ' * The per-component .d.ts files from project/components, flattened into one',
  ' * declaration file. They are authored to be read next to their component, so',
  ' * they use the ambient React namespace and cross-reference each other by',
  ' * relative path; both are resolved here.',
  ' *',
  ' * JSX.Element is rewritten to React.JSX.Element, which resolves under both',
  ' * @types/react 18 and 19 — the global JSX namespace was removed in 19. */',
  '',
  "import * as React from 'react';",
  '',
];

for (const file of declFiles) {
  const rel = relative(join(PROJECT, 'components'), file).split('\\').join('/');
  const body = readFileSync(file, 'utf8')
    /* Cross-file type imports: everything lives in this one file now. */
    .replace(/^\s*import\s+type\s*\{[^}]*\}\s*from\s*'\.[^']*';?\s*$/gm, '')
    .replace(/^\s*import\s*\{[^}]*\}\s*from\s*'\.[^']*';?\s*$/gm, '')
    .replace(/\bJSX\.Element\b/g, 'React.JSX.Element');
  types.push('/* ' + rel + ' */');
  types.push(body.trim());
  types.push('');
}

writeFileSync(join(DIST, 'index.d.ts'), types.join('\n'));

/* --------------------------------------------------------------------- css */

/** Inlines the @import graph reachable from styles.css into one stylesheet. */
function inlineCss(entry, seen = new Set()) {
  const abs = resolve(entry);
  if (seen.has(abs)) return '';
  seen.add(abs);
  const css = readFileSync(abs, 'utf8');
  return css.replace(/@import\s+url\(["']([^"']+)["']\);?/g, (whole, href) => {
    if (/^https?:/.test(href)) return whole;
    const target = resolve(dirname(abs), href);
    if (!existsSync(target)) return whole;
    return (
      '\n/* ' + relative(PROJECT, target).split('\\').join('/') + ' */\n' +
      inlineCss(target, seen)
    );
  });
}

let css = inlineCss(join(PROJECT, 'styles.css'));
/* Font URLs are relative to tokens/fonts.css in the source tree; in the package
   the stylesheet sits beside its own assets/ directory. */
css = css.replace(/url\(["']\.\.\/assets\/fonts\/([^"')]+)["']\)/g, 'url("./assets/fonts/$1")');

writeFileSync(
  join(DIST, 'styles.css'),
  '/* GENERATED by tools/build-package.mjs — the whole LAMP token and component\n' +
    '   stylesheet, with the @import graph inlined. Import it once at your app root. */\n' +
    css,
);

mkdirSync(join(DIST, 'assets/fonts'), { recursive: true });
for (const f of readdirSync(join(PROJECT, 'assets/fonts'))) {
  copyFileSync(join(PROJECT, 'assets/fonts', f), join(DIST, 'assets/fonts', f));
}

/* ------------------------------------------------------------------ report */

const size = (f) => (statSync(join(DIST, f)).size / 1024).toFixed(0) + 'kB';
const exported = [...bySource.values()].reduce((a, n) => a + n.length, 0);
console.log(
  `@lamp/design-system  ${exported} exports  ` +
    `index.mjs ${size('index.mjs')}  index.cjs ${size('index.cjs')}  ` +
    `index.d.ts ${size('index.d.ts')}  styles.css ${size('styles.css')}`,
);
